config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'portfolio'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page_view, name='home'),
    path('courses', views.courses_page_view, name='courses'),
    path('playground', views.playground_page_view, name='playground'),
    path('sitemap', views.sitemap_page_view, name='sitemap'),
    path('der', views.der_page_view, name='der'),
    path('blog/', views.blog_page_view, name='blog'),
    path('webDev', views.webDev_page_view, name='webDev'),
    path('article/<int:article_id>/', views.article_page_view, name='article'),
    path('add_author', views.add_author_page_view, name='add_author'),
    path('add_article', views.add_article_page_view, name='add_article'),
    path('edit_article/<int:article_id>/', views.edit_article_page_view, name='edit_article'),
    path('remove_article/<int:article_id>/', views.remove_article, name='remove_article'),
    path('add_curricularUnit', views.add_curricularUnit_page_view, name='add_curricularUnit'),
    path('edit_curricularUnit/<int:curricularUnit_id>', views.edit_curricularUnit_page_view, name='edit_curricularUnit'),
    path('remove_curricularUnit/<int:curricularUnit_id>', views.remove_curricularUnit, name='remove_curricularUnit'),
    path('add_project', views.add_project_page_view, name='add_project'),
    path('edit_project/<int:project_id>/', views.edit_project_page_view, name='edit_project'),
    path('remove_project/<int:project_id>/', views.remove_project, name='remove_project'),
    path('login/', views.login_page_view, name='login'),
    path('logout', views.logout_page_view, name='logout'),
]

portfolio/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


# Create your models here.

# ------BLOG-------------------------------------------------------------------------------------------------------------
class Author(models.Model):
    name = models.CharField(max_length=50)


    def __str__(self):
        return self.name


class Article(models.Model):
    Business = 'Business'
    Technology = 'Technology'
    Entertainment = 'Entertainment'
    Lifestyle = 'Lifestyle'
    Travel = 'Travel'
    Sports = 'Sports'
    Other = 'Other'

    CHOICES_TYPE = [
        (Business, "Business"),
        (Technology, 'Technology'),
        (Entertainment, 'Entertainment'),
        (Lifestyle, 'Lifestyle'),
        (Travel, 'Travel'),
        (Sports, 'Sports'),
        (Other, 'Other')
    ]
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='portfolio/static/portfolio/images/', default='url("../images/backiee-5769412.jpg")')
    area = models.CharField(max_length=15, choices=CHOICES_TYPE, default="Business")
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='authors', default='')
    brief_description = models.CharField(max_length=500)
    sub_title1 = models.CharField(max_length=100, null=True, blank=True, default='')
    description1 = models.CharField(max_length=1000, null=True, blank=True, default='')
    sub_title2 = models.CharField(max_length=100, null=True, blank=True, default='')
    description2 = models.CharField(max_length=1000, null=True, blank=True, default='')
    date = models.DateField()

    def __str__(self):
        return self.title


# ------COURSES----------------------------------------------------------------------------------------------------------
class Certification(models.Model):
    certification = models.CharField(max_length=50)

    def __str__(self):
        return self.certification


class OtherCourse(models.Model):
    course = models.CharField(max_length=70)

    def __str__(self):
        return self.course


class Teacher(models.Model):
    name = models.CharField(max_length=50)
    link = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.name


class Academic(models.Model):
    academic = models.CharField(max_length=50)

    def __str__(self):
        return self.academic


class CurricularUnit(models.Model):
    curricular_unit = models.CharField(max_length=50, default='')
    link = models.URLField()
    year = models.CharField(max_length=5, default='')
    semester = models.CharField(max_length=5, default='1')
    ects = models.IntegerField(default=1)
    responsible_teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='responsible_teachers',
                                            null=True, blank=True, default='')
    additional_teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='additional_teachers',
                                           null=True, blank=True, default='')
    ranking = models.PositiveIntegerField(default=5, validators=[MinValueValidator(1), MaxValueValidator(5)])
    academic = models.ForeignKey(Academic, on_delete=models.CASCADE, related_name='curricular_units')

    def __str__(self):
        return self.curricular_unit


# -------PROJECTS--------------------------------------------------------------------------------------------------------
class Project(models.Model):
    title = models.CharField(max_length=50, default='')
    curricular_unit = models.CharField(max_length=50, default='')
    description = models.CharField(max_length=500, default='')
    image = models.ImageField(upload_to='portfolio/static/portfolio/images/', default='url("../images/backiee-5769412.jpg")')

    def __str__(self):
        return self.title


# -------WEB DEV--------------------------------------------------------------------------------------------------------
class Subject(models.Model):
    name = models.CharField(max_length=30, default='')
    description = models.CharField(max_length=500, default='')

    def __str__(self):
        return self.name


class Tech_BackEnd(models.Model):
    name = models.CharField(max_length=10, default='')
    release_year = models.PositiveIntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2100)])
    author = models.CharField(max_length=50, default='')
    logo = models.ImageField(upload_to='portfolio/images/')
    website_link = models.URLField()
    description = models.CharField(max_length=800, default='')
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True, blank=True, related_name='be_techs')

    def __str__(self):
        return self.name


class Tech_FrontEnd(models.Model):
    name = models.CharField(max_length=10, default='')
    release_year = models.PositiveIntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2100)])
    author = models.CharField(max_length=50, default='')
    logo = models.ImageField(upload_to='portfolio/images/')
    website_link = models.URLField()
    description = models.CharField(max_length=800, default='')
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True, blank=True, related_name='fe_techs')

    def __str__(self):
        return self.name


class Tech_Other(models.Model):
    name = models.CharField(max_length=10, default='')
    release_year = models.PositiveIntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2100)])
    author = models.CharField(max_length=50, default='')
    logo = models.ImageField(upload_to='portfolio/images/')
    website_link = models.URLField()
    description = models.CharField(max_length=800, default='')
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True, blank=True, related_name='other_techs')

    def __str__(self):
        return self.name

portfolio/forms.py
from django.forms import ModelForm
from .models import *


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = '__all__'


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = '__all__'


class CurricularUnitForm(ModelForm):
    class Meta:
        model = CurricularUnit
        fields = '__all__'


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = '__all__'

portfolio/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import *
from .models import *


# Create your views here.

def home_page_view(request):
    ProjectsList = Project.objects.all()
    context = {'ProjectsList': ProjectsList}
    return render(request, 'portfolio/home.html', context)


def courses_page_view(request):
    AcademicsList = Academic.objects.all()
    CurricularUnitsList = CurricularUnit.objects.all()
    OtherCoursesList = OtherCourse.objects.all()
    CertificationsList = Certification.objects.all()
    context = {'AcademicsList': AcademicsList,
               'OtherCoursesList': OtherCoursesList,
               'CertificationsList': CertificationsList,
               'CurricularUnitsList': CurricularUnitsList}
    return render(request, 'portfolio/courses.html', context)



def playground_page_view(request):
    return render(request, 'portfolio/playground.html')


def blog_page_view(request):
    ProjectsList = Project.objects.all()

    articles_All = Article.objects.all()
    articles_Business = Article.objects.all().filter(area='Business')
    articles_Technology = Article.objects.all().filter(area='Technology')
    articles_Entertainment = Article.objects.all().filter(area='Entertainment')
    articles_Lifestyle = Article.objects.all().filter(area='Lifestyle')
    articles_Travel = Article.objects.all().filter(area='Travel')
    articles_Sports = Article.objects.all().filter(area='Sports')
    articles_Other = Article.objects.all().filter(area='Other')
    context = {'articles_All': articles_All,
               'articles_Business': articles_Business,
               'articles_Technology': articles_Technology,
               'articles_Entertainment': articles_Entertainment,
               'articles_Lifestyle': articles_Lifestyle,
               'articles_Travel': articles_Travel,
               'articles_Sports': articles_Sports,
               'articles_Other': articles_Other,
               'ProjectsList': ProjectsList}
    return render(request, 'portfolio/blog.html', context)


def article_page_view(request, article_id):
    article = Article.objects.get(pk=article_id)
    context = {'article': article}
    return render(request, 'portfolio/article.html', context)


def webDev_page_view(request):
    be_subjects = Subject.objects.filter(name__startswith='Back')
    fe_subjects = Subject.objects.filter(name__startswith='Front')
    other_subjects = Subject.objects.filter(name__startswith='Other')
    backEndTechsList = Tech_BackEnd.objects.all()
    frontEndTechsList = Tech_FrontEnd.objects.all()
    otherTechsList = Tech_Other.objects.all()
    context = {'be_subjects': be_subjects,
               'fe_subjects': fe_subjects,
               'other_subjects': other_subjects,
               'backEndTechsList': backEndTechsList,
               'frontEndTechsList': frontEndTechsList,
               'otherTechsList': otherTechsList}
    return render(request, 'portfolio/webDev.html', context)


def der_page_view(request):
    return render(request, 'portfolio/der.html')


def sitemap_page_view(request):
    return render(request, 'portfolio/sitemap.html')


#AUTHENTICATION---------------------------------------------------------------------------------------------
def login_page_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect(reverse('portfolio:home'))
        else:
            return render(request, "portfolio/login.html", {
                'message': "Invalid credentials."
            })

    return render(request, 'portfolio/login.html')


def logout_page_view(request):
    logout(request)

    return render(request, 'portfolio/home.html')


#CRUD---------------------------------------------------------------------------------------------
@login_required
def add_author_page_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('portfolio:login'))

    form = AuthorForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))

    context = {'form': form}

    return render(request, 'portfolio/add_author.html', context)

@login_required
def add_article_page_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('portfolio:login'))

    form = ArticleForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))

    context = {'form': form}
    return render(request, 'portfolio/add_article.html', context)


@login_required
def add_curricularUnit_page_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('portfolio:login'))

    form = CurricularUnitForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:courses'))

    context = {'form': form}
    return render(request, 'portfolio/add_curricularUnit.html', context)


@login_required
def add_project_page_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('portfolio:login'))

    form = ProjectForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('portfolio:home')

    context = {'form': form}
    return render(request, 'portfolio/add_project.html', context)

@login_required
def edit_article_page_view(request, article_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('portfolio:login'))

    article = Article.objects.get(id=article_id)
    form = ArticleForm(request.POST or None, instance=article )
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))
    context = {'form': form, 'article_id': article_id}
    return render(request, 'portfolio/edit_article.html', context)


@login_required
def edit_curricularUnit_page_view(request, curricularUnit_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('portfolio:login'))

    curricularUnit = CurricularUnit.objects.get(id=curricularUnit_id)
    form = CurricularUnitForm(request.POST or None, instance=curricularUnit)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:courses'))
    context = {'form': form, 'curricularUnit_id': curricularUnit_id }
    return render(request, 'portfolio/edit_curricularUnit.html', context)


@login_required
def edit_project_page_view(request, project_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('portfolio:login'))

    project = Project.objects.get(id=project_id)
    form = ProjectForm(request.POST or None, instance=project)
    if form.is_valid():
        form.save()
        return redirect('portfolio:home')
    context = {'form': form, 'project_id': project_id }
    return render(request, 'portfolio/edit_project.html', context)

@login_required
def remove_article(request, article_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('portfolio:login'))
    Article.objects.get(id=article_id).delete()
    return HttpResponseRedirect(reverse('portfolio:blog'))

def remove_curricularUnit(request, curricularUnit_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('portfolio:login'))
    CurricularUnit.objects.get(id=curricularUnit_id).delete()
    return HttpResponseRedirect(reverse('portfolio:courses'))

@login_required
def remove_project(request, project_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('portfolio:login'))
    Project.objects.get(id=project_id).delete()
    return HttpResponseRedirect(reverse('portfolio:home'))

portfolio/templates/portfolio/blog.html
<!-- home.html -->

{% extends 'portfolio/layout.html' %}


{% load static %}

{% block main %}

<h1 class="titulo-pagina">BLOG</h1>
</br>
<div class="page_content_formatting_20">
    <div class="blog-page" class="blog">
        <div class="blog-button">
            <button class="borderless-button" onclick="showPage('ALL POSTS')"><a>All Posts</a></button>
            <button class="borderless-button" onclick="showPage('Business')"><a>Business</a></button>
            <button class="borderless-button" onclick="showPage('Technology')"><a>Technology</a></button>
            <button class="borderless-button" onclick="showPage('Entertainment')"><a>Entertainment</a></button>
            <button class="borderless-button" onclick="showPage('Lifestyle')"><a>Lifestyle</a></button>
            <button class="borderless-button" onclick="showPage('Travel')"><a>Travel</a></button>
            <button class="borderless-button" onclick="showPage('Sports')"><a>Sports</a></button>
            <button class="borderless-button" onclick="showPage('Other')"><a>Other</a></button>
        </div>
        </br></br></br>

        <div id="ALL POSTS" class="page active">

            <h2 class="blog-button">All Posts</h2>
            {% for article in articles_All %}
            <div class="blog">
                <div>
                    <div><img src="{{ article.image.url }}"></div>
                    <div class="blog-text">
                        <p>By <b>{{ article.author }}</b> | Updated {{ article.date }}</p></br>
                        <h3><b>{{ article.title }}</b></h3></br>
                        <p>{{ article.brief_description }}</p>
                        </br></br>
                        <p style="text-align: right; font-size: 0.8rem"><a style="text-decoration: none" href="{% url 'portfolio:article' article.id %}">Read
                            more</a></p>
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <div id="Business" class="page">
            <h2 class="blog-button">Business</h2>

            {% for article in articles_Business %}
            <div class="blog">
                <div>
                    <div><img src="{{ article.image.url }}"></div>
                    <div class="blog-text">
                        <p>By <b>{{ article.author }}</b> | Updated {{ article.date }}</p></br>
                        <h3><b>{{ article.title }}</b></h3></br>
                        <p>{{ article.brief_description }}</p>
                        </br></br>
                        <p style="text-align: right; font-size: 0.8rem"><a style="text-decoration: none" href="{% url 'portfolio:article' article.id %}">Read
                            more</a></p>
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <div id="Technology" class="page">
            <h2 class="blog-button">Technology</h2>

            {% for article in articles_Technology %}
            <div class="blog">
                <div>
                    <div><img src="{{ article.image.url }}"></div>
                    <div class="blog-text">
                        <p>By <b>{{ article.author }}</b> | Updated {{ article.date }}</p></br>
                        <h3><b>{{ article.title }}</b></h3></br>
                        <p>{{ article.brief_description }}</p>
                        </br></br>
                        <p style="text-align: right; font-size: 0.8rem"><a style="text-decoration: none" href="{% url 'portfolio:article' article.id %}">Read
                            more</a></p>
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <div id="Entertainment" class="page">
            <h2 class="blog-button">Entertainment</h2>

            {% for article in articles_Entertainment %}
            <div class="blog">
                <div>
                    <div><img src="{{ article.image.url }}"></div>
                    <div class="blog-text">
                        <p>By <b>{{ article.author }}</b> | Updated {{ article.date }}</p></br>
                        <h3><b>{{ article.title }}</b></h3></br>
                        <p>{{ article.brief_description }}</p>
                        </br></br>
                        <p style="text-align: right; font-size: 0.8rem"><a style="text-decoration: none" href="{% url 'portfolio:article' article.id %}">Read
                            more</a></p>
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <div id="Lifestyle" class="page">
            <h2 class="blog-button">Lifestyle</h2>

            {% for article in articles_Lifestyle %}
            <div class="blog">
                <div>
                    <div><img src="{{ article.image.url }}"></div>
                    <div class="blog-text">
                        <p>By <b>{{ article.author }}</b> | Updated {{ article.date }}</p></br>
                        <h3><b>{{ article.title }}</b></h3></br>
                        <p>{{ article.brief_description }}</p>
                        </br></br>
                        <p style="text-align: right; font-size: 0.8rem"><a style="text-decoration: none" href="{% url 'portfolio:article' article.id %}">Read
                            more</a></p>
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <div id="Travel" class="page">
            <h2 class="blog-button">Travel</h2>

            {% for article in articles_Travel %}
            <div class="blog">
                <div>
                    <div><img src="{{ article.image.url }}"></div>
                    <div class="blog-text">
                        <p>By <b>{{ article.author }}</b> | Updated {{ article.date }}</p></br>
                        <h3><b>{{ article.title }}</b></h3></br>
                        <p>{{ article.brief_description }}</p>
                        </br></br>
                        <p style="text-align: right; font-size: 0.8rem"><a style="text-decoration: none" href="{% url 'portfolio:article' article.id %}">Read
                            more</a></p>
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <div id="Sports" class="page">
            <h2 class="blog-button">Sports</h2>

            {% for article in articles_Sports %}
            <div class="blog">
                <div>
                    <div><img src="{{ article.image.url }}"></div>
                    <div class="blog-text">
                        <p>By <b>{{ article.author }}</b> | Updated {{ article.date }}</p></br>
                        <h3><b>{{ article.title }}</b></h3></br>
                        <p>{{ article.brief_description }}</p>
                        </br></br>
                        <p style="text-align: right; font-size: 0.8rem"><a style="text-decoration: none" href="{% url 'portfolio:article' article.id %}">Read
                            more</a></p>
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <div id="Other" class="page">
            <h2 class="blog-button">Other</h2>

            {% for article in articles_Other %}
            <div class="blog">
                <div>
                    <div><img src="{{ article.image.url }}"></div>
                    <div class="blog-text">
                        <p>By <b>{{ article.author }}</b> | Updated {{ article.date }}</p></br>
                        <h3><b>{{ article.title }}</b></h3></br>
                        <p>{{ article.brief_description }}</p>
                        </br></br>
                        <p style="text-align: right; font-size: 0.8rem"><a style="text-decoration: none" href="{% url 'portfolio:article' article.id %}">Read
                            more</a></p>

                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        </br>
        {% if user.is_authenticated %}
        <h4 style="text-align: center"><a style="text-decoration: none" href="{% url 'portfolio:add_author' %}">Add Author</a> |
            <a style="text-decoration: none" href="{% url 'portfolio:add_article' %}">Add new Article</a>  </h4>
        {% endif %}
    </div>

</div>
</br></br></br></br></br>
{% endblock %}

portfolio/templates/portfolio/layout.html
<!doctype html>
<html lang="en">
<head>
    <title>MSoares Portfolio</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="Miguel Soares">
    <meta name="description" content="O meu portfólio">


    {% load static %}
    <link rel="stylesheet"  href="{% static 'portfolio/css/style-light.css' %}" >
    <link rel="icon" type="image/x-icon" href="{% static 'portfolio/images/MS9.png' %}" sizes="any">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;1,100;1,200;1,300&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Monoton&display=swap" rel="stylesheet">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>

    {% load static %}
    <script type="application/javascript" src="{% static 'portfolio/js/script.js' %}"></script>
    <script src="https://kit.fontawesome.com/fa5f8f8cfb.js" crossorigin="anonymous"></script>

</head>

<body onload="loadStyle()">

<div class="grid-container">
    <name class="name-container">
        <p class="name-style">MIGUEL SOARES</p>
    </name>
    <menu class="menu-container">
        <nav>
            <a href="{% url 'portfolio:home' %}">HOME</a>
            <div class="dropdown">
                <button class="dropbtn">
                    <a href="#">ABOUT</a>
                </button>
                <div class="dropdown-content">
                    <a href="{% url 'portfolio:home' %}#aboutMe">ME</a>
                    <a href="{% url 'portfolio:home' %}#projects">MY PROJECTS</a>
                    <a href="{% url 'portfolio:courses' %}">MY EDUCATION</a>
                    {% load static %}
                    <a href="{% static 'portfolio/images/MIGUELSOARES_RESUME_EN_2023.pdf' %}" target="blank_">MY
                        RESUME</a>
                </div>
            </div>
            <a href="{% url 'portfolio:playground' %}">PLAYGROUND</a>
            <a href="{% url 'portfolio:webDev' %}">WEBDEV</a>
            <a href="{% url 'portfolio:blog' %}">BLOG</a>
            <div class="dropdown">
                <button class="dropbtn">
                    <a href="#">LABS</a>
                </button>
                <div class="dropdown-content">
                    <a href="http://pwmsoares.pythonanywhere.com/" target="blank_">LAB1</a>
                    <a href="http://pwmsoares.pythonanywhere.com/index.html" target="blank_">LAB2</a>
                    <a href="http://pwmsoares.pythonanywhere.com/lab3/index.html" target="blank_">LAB3</a>
                    <a href="https://pwmsoares.pythonanywhere.com/lab4/index.html" target="blank_">LAB4</a>
                </div>
            </div>
            <div class="dropdown">
                <button class="dropbtn">
                    <a href="#">WEBSITE</a>
                </button>
                <div class="dropdown-content">
                    <a href="{% url 'portfolio:sitemap' %}">SITEMAP</a>
                    <a href="{% url 'portfolio:der' %}">ERD</a>
                </div>
            </div>

            {% if user.is_authenticated %}
            <a href="{% url 'portfolio:logout' %}">Logout ({{user.username}})</a>
            {% else %}
            <a href="{% url 'portfolio:login' %}">LOGIN</a>
            {% endif %}
        </nav>
        <button><span class="material-symbols-outlined" id="darkModeBtn">clear_day</span></button>
    </menu>

    <main>
        {% block main %}
        {% endblock main %}
    </main>


    <footer>
        <div class="footer-conteiner">

            <div class="footer-col-1">
                <h4 class="footer-header">Useful Links</h4>
                <ul>
                    <li><a href="{% url 'portfolio:home' %}#aboutMe">About Me</a></li>
                    <li><a href="{% url 'portfolio:sitemap' %}">Site Map</a></li>
                    <li><a href="https://www.ulusofona.pt/" target="_blank">U.Lusófona</a></li>
                </ul>
            </div>
            <div class="footer-col-2">
                <h4 class="footer-header">Author</h4>
                <ul>
                    <li>
                        <p>Miguel Soares | 21706025</p>
                    </li>
                    <li>
                        <p>Universidade Lusófona</p>
                    </li>
                    <li>
                        <p>2023</p>
                    </li>
                </ul>
            </div>
            <div class="footer-col-2">
                <h4 class="footer-header">Contact</h4>
                <ul>
                    <li>
                        <p><i class="fa-solid fa-house"></i> Rua do Miguel 1, 1600-000 Lisboa</p>
                    </li>
                    <li>
                        <p><i class="fa-solid fa-envelope"></i> miguel.m.soares@netcabo.pt</p>
                    </li>
                    <li>
                        <p><i class="fa-solid fa-mobile-screen-button"></i> 987654321</p>
                    </li>
                </ul>
            </div>
            <div class="footer-col-3">
                <h4 class="footer-header">Follow Me</h4>
                <div class="social-links">
                    <a href="https://www.facebook.com/miguel.soares.12576" target="_blank"><i
                            class="fa-brands fa-facebook-f"></i></a>
                    <a href="https://www.linkedin.com/in/miguel-morais-soares/" target="_blank"><i
                            class="fa-brands fa-linkedin-in"></i></a>
                    <a href="https://github.com/MiguelMSoares21706025" target="_blank"><i
                            class="fa-brands fa-github"></i></a>
                </div>
            </div>

        </div>

    </footer>

</div>
</body>

</html>